/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IInvite } from "../IInvite";

export class IInvite__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInvite {
    return new Contract(address, _abi, signerOrProvider) as IInvite;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_userAddr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_power",
        type: "uint256",
      },
    ],
    name: "redeemPower",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_userAddr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_power",
        type: "uint256",
      },
    ],
    name: "referReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
