/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IInviteInterface extends ethers.utils.Interface {
  functions: {
    "redeemPower(address,uint256)": FunctionFragment;
    "referReward(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "redeemPower",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "referReward",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "redeemPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referReward",
    data: BytesLike
  ): Result;

  events: {};
}

export class IInvite extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IInviteInterface;

  functions: {
    redeemPower(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "redeemPower(address,uint256)"(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    referReward(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "referReward(address,uint256)"(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  redeemPower(
    _userAddr: string,
    _power: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "redeemPower(address,uint256)"(
    _userAddr: string,
    _power: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  referReward(
    _userAddr: string,
    _power: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "referReward(address,uint256)"(
    _userAddr: string,
    _power: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    redeemPower(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "redeemPower(address,uint256)"(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    referReward(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "referReward(address,uint256)"(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    redeemPower(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "redeemPower(address,uint256)"(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    referReward(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "referReward(address,uint256)"(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    redeemPower(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "redeemPower(address,uint256)"(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    referReward(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "referReward(address,uint256)"(
      _userAddr: string,
      _power: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
